# 一键安装（Windows PowerShell）
$ErrorActionPreference = "Stop"
$root = "C:\app\dfy"
Write-Host "== 建目录 ==" -ForegroundColor Cyan
New-Item -ItemType Directory -Force -Path $root, "$root\panel", "$root\logs" | Out-Null
Write-Host "== 复制文件 ==" -ForegroundColor Cyan
Copy-Item -Recurse -Force ".\panel\*" "$root\panel\"
Copy-Item -Force ".\scripts\*" "$root\"
$py = (Get-Command python -ErrorAction SilentlyContinue)
if (-not $py) { Write-Host "!! 没找到 python，请先装 Python 3.8+" -ForegroundColor Red; exit 1 }
Write-Host "== 建计划任务（每 5 分钟：归档 → 分段 → 记忆同步 → 记忆卡 → 哨兵）==" -ForegroundColor Cyan
$vbs = "$root\archive-history.vbs"
$lines = @(
  "' auto-generated by install.ps1",
  'Set sh = CreateObject("WScript.Shell")',
  'q = Chr(34)',
  'py = "' + $py.Source + '"'
)
foreach ($s in @("history_archive.py","history_rotate.py","memory_sync.py","memory_digest.py","session_guard.py")) {
  $lines += 'sh.Run q & py & q & " " & q & "' + $root + '\' + $s + '" & q, 0, False'
  $lines += 'WScript.Sleep 8000'
}
$lines | Set-Content -Path $vbs -Encoding ascii
schtasks /create /tn "WhaleHistory" /tr "wscript.exe \"$vbs\"" /sc minute /mo 5 /f | Out-Null
Write-Host "== 完成 ==" -ForegroundColor Green
Write-Host "下一步：python $root\panel\server.py --port 8787"
